import mongoose, { Schema } from 'mongoose';

const surveySchema = new mongoose.Schema({
    user_id: {
        type: Schema.Types.ObjectId,
        ref: 'User', // This refers to the 'User' model
        required: true,
        unique: true, // Ensures one-to-one relationship
    },
    q1NG: Boolean,
    q1ET: Boolean,
    q1TG: Boolean,
    q1ZA: Boolean,
    q1GH: Boolean,
    q1Zambia: Boolean,
    q1Text: String,
    q2wildlife: Boolean,
    q2historical: Boolean,
    q2cultural: Boolean,
    q2adventure: Boolean,
    q2food: Boolean,
    q2entertainment: Boolean,
    q2Text: String,
    q3airplane: Boolean,
    q3public: Boolean,
    q3car: Boolean,
    q3bicycle: Boolean,
    q3notSure: Boolean,
    q4exploreDest: Boolean,
    q4recieveFlightInfo: Boolean,
    q4accessAirportInfo: Boolean,
    q4findAccom: Boolean,
    q4utilizeLangTrans: Boolean,
    q4planActivities: Boolean,
    q4noneOfAbove: Boolean,
    q5FlightAirportInfo: Boolean,
    q5AccomOptions: Boolean,
    q5Weather: Boolean,
    q5ActivityRecs: Boolean,
    q5LangTrans: Boolean,
    q5Text: String,
    q6Hotels: Boolean,
    q6Hostels: Boolean,
    q6VacaRentals: Boolean,
    q6Camping: Boolean,
    q6notSure: Boolean,
    q7LessThanWeek: Boolean,
    q7_1_2Weeks: Boolean,
    q7_1_3Months: Boolean,
    q7_3MonthsToYear: Boolean,
    q7MoreThanYear: Boolean,
    q8_1: Boolean,
    q8_2: Boolean,
    q8_3: Boolean,
    q8_4: Boolean,
    q8_5: Boolean,
    q8PreferNotSay: Boolean,
    q9Solo: Boolean,
    q9Family: Boolean,
    q9Friends: Boolean,
    q9Partner: Boolean,
    q9Group: Boolean,
    q10English: Boolean,
    q10French: Boolean,
    q10Arabic: Boolean,
    q10Spanish: Boolean,
    q10Text: String,
});

const Survey = mongoose.models.surveys || mongoose.model('surveys', surveySchema);
export default Survey;
